Repository IBM/sarama, pull requests merged in 2022-09, with the labels that each got.

#2335 chore(deps): bump module github.com/pierrec/lz4/v4 to v4.1.16
  go.mod
  go.sum
Labels: dependencies, bump/patch

#2317 fix(consumer): avoid pushing unrelated responses to paused children
  consumer.go
Labels: fix

#2328 feat: support key in MockFetchResponse.
  consumer_test.go
  mockresponses.go
Labels: feat

#2339 feat(consumer): support multiple balance strategies
  config.go
  consumer_group.go
  consumer_group_test.go
  examples/consumergroup/main.go
  functional_consumer_group_test.go
Labels: feat

#2331 fix: race condition(may panic) when closing consumer group
  consumer_group.go
Labels: fix

#2345 fix(consumer): default ResetInvalidOffsets to true
  config.go
Labels: fix

#2346 chore(ci): bump kafka-versions to latest
  .github/workflows/fvt.yml
  Dockerfile.kafka
  docker-compose.yml
  entrypoint.sh
  functional_test.go
  utils.go
Labels: chore

#2334 chore(deps): bump golang.org/x/sync digest to 7f9b162
  go.mod
  go.sum
Labels: dependencies, bump/digest

#2348 chore(deps): bump golang.org/x/net digest to f486391
  go.mod
  go.sum
Labels: dependencies, bump/digest

#2336 chore(deps): bump module github.com/shopify/toxiproxy/v2 to v2.5.0
  go.mod
  go.sum
Labels: dependencies, bump/minor

#2349 chore(deps): bump module github.com/klauspost/compress to v1.15.11
  go.mod
  go.sum
Labels: dependencies, bump/patch

#2327 Validate the `Config` when creating a mock producer/consumer
  mocks/async_producer.go
  mocks/async_producer_test.go
  mocks/consumer.go
  mocks/consumer_test.go
  mocks/sync_producer.go
  mocks/sync_producer_test.go
Labels: fix
