Repository IBM/sarama, pull requests merged in 2022-02, with the labels that each got.

#2127 Backport missing changelog entries from 1.28 onwards
  CHANGELOG.md
Labels: chore

#2130 fix: rework RebalancingMultiplePartitions test
  consumer_test.go
Labels: internal

#1939 fix(test): use Sarama transactional producer
  functional_consumer_test.go
  functional_test.go
Labels: internal

#2159 chore: refresh dependencies to latest
  go.mod
  go.sum
Labels: deps

#2154 fix: TestRecordBatchDecoding failing sporadically
  record_test.go
Labels: fix

#2131 feat: make `ErrOutOfBrokers` wrap the underlying error that prevented connections to the brokers
  .gitignore
  .golangci.yml
  admin.go
  admin_test.go
  async_producer.go
  async_producer_test.go
  broker.go
  broker_test.go
  client.go
  client_test.go
  config_test.go
  consumer.go
  consumer_group.go
  consumer_group_members.go
  consumer_metadata_response_test.go
  consumer_test.go
  create_partitions_response.go
  create_partitions_response_test.go
  create_topics_response.go
  create_topics_response_test.go
  delete_groups_response_test.go
  describe_groups_response_test.go
  errors.go
  errors_test.go
  fetch_response.go
  fetch_response_test.go
  functional_client_test.go
  functional_consumer_group_test.go
  functional_consumer_test.go
  functional_producer_test.go
  functional_test.go
  go.mod
  go.sum
  heartbeat_response_test.go
  join_group_response_test.go
  leave_group_response_test.go
  list_groups_response_test.go
  message_set.go
  metadata_response_test.go
  mockbroker.go
  mocks/async_producer.go
  mocks/async_producer_test.go
  mocks/consumer_test.go
  mocks/mocks.go
  mocks/sync_producer.go
  mocks/sync_producer_test.go
  offset_manager_test.go
  offset_response_test.go
  produce_response_test.go
  record_batch.go
  sasl_handshake_response_test.go
  sync_group_response_test.go
  sync_producer_test.go
Labels: breaking

#2109 fix: avoid starvation in subscriptionManager
  consumer.go
Labels: fix
