Repository IBM/sarama, pull requests merged in 2022-01, with the labels that each got.

#2096 fix: ignore non-nil but empty error strings in Describe/Alter client quotas responses
  admin.go
  functional_admin_test.go
Labels: fix

#2100 chore: bump runtime and test dependencies
  docker-compose.yml
  functional_test.go
  go.mod
  go.sum
Labels: chore

#2084 Fix typo
  examples/sasl_scram_client/README.md
Labels: cla-needed

#2094 Support request pipelining in AsyncProducer
  async_producer.go
  broker.go
  broker_test.go
  config.go
Labels: feat

#2113 Fix typo
  examples/http_server/http_server.go
Labels: cla-needed
