Repository IBM/sarama, pull requests merged in 2022-08, with the labels that each got.

#2301 chore(deps): bump golang.org/x/net digest to c7608f3
  go.mod
  go.sum
Labels: dependencies, bump/digest

#2300 chore: add kafka 3.1.1 to the version matrix
  .github/workflows/fvt.yml
  Dockerfile.kafka
  docker-compose.yml
  entrypoint.sh
  functional_test.go
  utils.go
  utils_test.go
Labels: chore

#2311 chore(deps): bump golangci/golangci-lint-action action to v3
  .github/workflows/ci.yml
  async_producer_test.go
  balance_strategy.go
  broker.go
  config.go
  describe_groups_response.go
  offset_response.go
  sarama.go
  utils.go
Labels: dependencies, bump/major

#2307 chore(deps): bump golang.org/x/net digest to 07c6da5
  go.mod
  go.sum
Labels: dependencies, bump/digest

#2313 chore(deps): bump github actions versions (major)
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/fuzz.yml
  .github/workflows/fvt.yml
Labels: dependencies, bump/major

#2252 feat: add option to propagate OffsetOutOfRange error
  config.go
  consumer_group.go
Labels: feat

#2143 fix(consumer): avoid submitting empty fetch requests when paused
  consumer.go
Labels: fix

#2299 feat(metrics): track consumer fetch request rates
  balance_strategy.go
  broker.go
  broker_test.go
  consumer_group_members_test.go
  consumer_metadata_response_test.go
  describe_groups_response.go
  encoder_decoder.go
  fetch_request.go
  fetch_response.go
  functional_producer_test.go
  join_group_response.go
  message_test.go
  metrics_test.go
  packet_decoder.go
  real_decoder.go
  record_batch.go
  records_test.go
  request.go
  request_test.go
  sarama.go
  sync_group_response.go
Labels: feat
