Repository IBM/sarama, pull requests merged in 2022-06, with the labels that each got.

#2236 chore(ci): experiment with using tparse
  .gitignore
  Makefile
Labels: ci

#2240 fix: check session.Context().Done() in examples/consumergroup
  examples/consumergroup/main.go
Labels: fix

#2242 chore(deps): bump thirdparty dependencies to latest releases
  docker-compose.yml
  go.mod
  go.sum
Labels: chore

#2245 fix: range balance strategy not like reference
  balance_strategy.go
  balance_strategy_test.go
Labels: fix
