Repository IBM/sarama, pull requests merged in 2023-08, with the labels that each got.

#2536 feat: sleep when throttled (KIP-219)
  broker.go
  broker_test.go
Labels: feat

#2543 Merge the two CONTRIBUTING.md's
  .github/CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: chore

#2544 fix(consumer): use newer LeaveGroup as appropriate
  consumer_group.go
Labels: fix

#2541 Add support for up to version 4 List Groups API
  broker.go
  list_groups_request.go
  list_groups_request_test.go
  list_groups_response.go
  list_groups_response_test.go
Labels: feat

#2545 Fix printing of final metrics
  tools/kafka-producer-performance/main.go
Labels: fix

#2548 fix(proto): ensure req+resp requiredVersion match
  describe_configs_request.go
  describe_configs_response.go
  request_test.go
Labels: fix

#2557 chore(ci): tidyup and improve actions workflows
  .github/workflows/apidiff.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/fuzz.yml
  .github/workflows/fvt.yml
  .github/workflows/stale.yml
Labels: ci

#2558 fix(proto): use fuller ranges of supported proto
  admin.go
  client.go
  consumer_group.go
  heartbeat_request.go
  heartbeat_response.go
  leave_group_request.go
  leave_group_response.go
  offset_fetch_request.go
  offset_fetch_response.go
Labels: fix

#2563 fix(consumer): cannot automatically fetch newly-added partitions unless restart
  consumer_group.go
  functional_consumer_group_test.go
  functional_test.go
Labels: fix

#2560 bug: implement unsigned modulus for partitioning with crc32 hashing
  partitioner.go
  partitioner_test.go
Labels: fix

#2565 fix(proto): use full range of SyncGroupRequest
  .pre-commit-config.yaml
  consumer_group.go
  mockresponses.go
  sync_group_request.go
  sync_group_response.go
Labels: fix

#2568 fix(proto): use full range of ListGroupsRequest
  admin.go
  mockresponses.go
Labels: fix

#2566 feat(proto): support for Metadata V6-V10
  async_producer_test.go
  broker.go
  consumer_group_test.go
  metadata_request.go
  metadata_request_test.go
  metadata_response.go
  metadata_response_test.go
  mockbroker.go
  mockresponses.go
Labels: feat

#2572 chore(config): make DefaultVersion V2_0_0_0
  config.go
  utils.go
Labels: feat

#2575 chore(test): ensure MockBroker closed within test
  broker_test.go
  client_test.go
  consumer_group_test.go
  offset_manager_test.go
  sarama_test.go
Labels: internal

#2574 chore(config): make DefaultVersion V2_1_0_0
  utils.go
Labels: breaking

#2579 chore(test): speedup some slow tests
  async_producer_test.go
  client_tls_test.go
  config_test.go
  consumer_group_test.go
  consumer_test.go
  functional_admin_test.go
  functional_client_test.go
  functional_consumer_follower_fetch_test.go
  functional_consumer_group_test.go
  functional_consumer_staticmembership_test.go
  functional_consumer_test.go
  functional_offset_manager_test.go
  functional_producer_test.go
  functional_test.go
  mockbroker.go
  mockresponses.go
  mocks/async_producer_test.go
  mocks/mocks.go
  mocks/sync_producer_test.go
  sarama_test.go
Labels: internal

#2589 chore(deps): bump module github.com/pierrec/lz4/v4 to v4.1.18
  go.mod
  go.sum
Labels: dependencies, bump/patch

#2587 chore(deps): bump module github.com/jcmturner/gokrb5/v8 to v8.4.4
  go.mod
  go.sum
Labels: dependencies, bump/patch

#2586 chore(deps): bump github.com/eapache/go-xerial-snappy digest to c322873
  go.mod
  go.sum
Labels: dependencies, bump/digest

#2588 chore(deps): bump module github.com/klauspost/compress to v1.16.7
  go.mod
  go.sum
Labels: dependencies, bump/patch

#2594 fix(test): add missing closes to admin client tests
  admin_test.go
  functional_admin_test.go
  functional_consumer_staticmembership_test.go
Labels: fix

#2595 fix(test): ensure some more clients are closed
  client_test.go
  functional_producer_test.go
  internal/toxiproxy/client.go
Labels: fix

#2600 feat(gzip): switch to klauspost/compress gzip
  compress.go
  config.go
  decompress.go
  message_test.go
  record_test.go
  request_test.go
Labels: feat

#2601 feat(fvt): add healthcheck, depends_on and --wait
  .github/workflows/fvt.yml
  docker-compose.yml
  functional_test.go
Labels: ci

#2612 fix(fvt): Metadata version in ensureFullyReplicated
  functional_test.go
Labels: ci

#2614 fix(examples): sync exactly_once and consumergroup
  examples/consumergroup/go.mod
  examples/consumergroup/go.sum
  examples/consumergroup/main.go
  examples/exactly_once/go.mod
  examples/exactly_once/go.sum
  examples/exactly_once/main.go
Labels: fix

#2609 fix(test): flaky test TestFuncOffsetManager
  functional_offset_manager_test.go
Labels: fix

#2599 chore: use go install for installing sarama tools
  tools/README.md
Labels: docs

#2618 fix(proto): handle V3 member metadata and empty owned partitions
  consumer_group_members.go
  consumer_group_members_test.go
Labels: fix

#2386 fix(doc): add missing doc for mock consumer
  mocks/consumer.go
Labels: docs

#2627 chore(proto): doc CreateTopics/JoinGroup fields
  create_topics_request.go
  create_topics_response.go
  join_group_request.go
  join_group_response.go
Labels: docs
