Repository IBM/sarama, pull requests merged in 2023-10, with the labels that each got.

#2663 fix: pre-compile regex for parsing kafka version
  utils.go
Labels: fix, performance

#2690 chore(doc): add OpenSSF badge
  README.md
Labels: ignore-for-release

#2039 feat(test): add a simple fuzzing example
  .github/workflows/fuzz.yml
  encoder_decoder_fuzz_test.go
  fetch_request.go
  record_batch.go
Labels: tests, ignore-for-release

#2693 Asynchronously close brokers during a RefreshBrokers
  client.go
Labels: fix
