Repository IBM/sarama, pull requests merged in 2023-07, with the labels that each got.

#2494 fix: restore (*OffsetCommitRequest) AddBlock func
  offset_commit_request.go
  offset_commit_request_test.go
  offset_manager.go
Labels: fix, breaking

#2504 chore(ci): bump golangci version, cleanup, depguard config
  .github/workflows/ci.yml
  .golangci.yml
Labels: ci

#2514 Clean up some typos and docs/help mistakes
  Dockerfile.kafka
  acl_create_request_test.go
  acl_describe_request.go
  acl_types.go
  add_partitions_to_txn_request.go
  async_producer.go
  balance_strategy.go
  broker.go
  client.go
  client_test.go
  consumer_group.go
  describe_configs_request_test.go
  errors.go
  heartbeat_request_test.go
  join_group_response_test.go
  message_test.go
  offset_manager.go
  packet_decoder.go
  sarama.go
  sync_producer.go
  tools/kafka-producer-performance/main.go
  transaction_manager.go
Labels: chore

#2517 Fix some retry issues
  admin.go
  admin_test.go
  client.go
Labels: fix

#2519 fix: admin retry logic
  admin.go
  admin_test.go
Labels: fix

#2457 feat: support for Kerberos authentication with a credentials cache.
  config.go
  config_test.go
  gssapi_kerberos.go
  kerberos_client.go
  kerberos_client_test.go
Labels: feat

#2520 Add some retry logic to more admin client functions
  admin.go
Labels: fix

#2528 fix: correct unsupported version check
  metadata_request.go
Labels: fix

#2532 fix: avoiding burning cpu if all partitions are paused
  consumer.go
Labels: fix
