Repository IBM/sarama, pull requests merged in 2023-11, with the labels that each got.

#2698 Fix data race on Broker.done channel
  broker.go
Labels: fix

#2678 fix: data race in Broker.AsyncProduce
  broker.go
Labels: fix

#2700 Fix default retention time value in offset commit
  offset_manager.go
  offset_manager_test.go
Labels: fix

#2701 fix(txmgr): ErrOffsetsLoadInProgress is retriable
  errors.go
  mockresponses.go
  transaction_manager.go
  transaction_manager_test.go
Labels: fix

#2706 fix(config): relax ClientID validation after 1.0.0
  config.go
  config_test.go
  mocks/async_producer_test.go
  mocks/consumer_test.go
  mocks/sync_producer_test.go
Labels: fix

#2711 chore: update CHANGELOG.md to v1.42.1
  CHANGELOG.md
Labels: ignore-for-release

#2713 feat: update go directive to 1.18
  .github/workflows/ci.yml
  encoder_decoder_fuzz_test.go
  functional_admin_test.go
  functional_client_test.go
  functional_consumer_follower_fetch_test.go
  functional_consumer_group_test.go
  functional_consumer_staticmembership_test.go
  functional_consumer_test.go
  functional_offset_manager_test.go
  functional_producer_test.go
  functional_test.go
  go.mod
  go.sum
  sarama_test.go
Labels: feat
