Repository IBM/sarama, pull requests merged in 2024-01, with the labels that each got.

#2717 fix: prevent ConsumerGroup.Close infinitely locking
  consumer_group.go
Labels: fix

#2472 feat: return KError instead of errors in AlterConfigs and DescribeConfig
  admin.go
  alter_configs_response.go
  describe_configs_response.go
Labels: stale/exempt, needs-investigation

#2721 fix(test): retry MockBroker Listen for EADDRINUSE
  mockbroker.go
Labels: tests
