Repository IBM/sarama, pull requests merged in 2024-02, with the labels that each got.

#2802 Use %v formatting words and remove unnecessary newline
  interceptors.go
Labels: fix

#2796 chore(doc): add v1.42.2 to CHANGELOG.md
  CHANGELOG.md
Labels: chore

#2795 feat: update go directive to 1.19
  .github/workflows/apidiff.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/fuzz.yml
  .github/workflows/fvt-main.yml
  .github/workflows/fvt-pr.yml
  .github/workflows/fvt.yml
  examples/consumergroup/go.mod
  examples/consumergroup/go.sum
  examples/exactly_once/go.mod
  examples/exactly_once/go.sum
  examples/http_server/go.mod
  examples/http_server/go.sum
  examples/interceptors/go.mod
  examples/interceptors/go.sum
  examples/sasl_scram_client/go.mod
  examples/sasl_scram_client/go.sum
  examples/txn_producer/go.mod
  examples/txn_producer/go.sum
  go.mod
Labels: feat

#2807 feat: add BuildSpnFunc to GSSAPIConfig for allow custom spn
  gssapi_kerberos.go
Labels: feat

#2804 fix: message.max.bytes should default to 1048576 not 1 MB
  config.go
Labels: fix

#2812 chore(ci): disable checkout credentials persist
  .github/workflows/apidiff.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/dependency-review.yml
  .github/workflows/fuzz.yml
  .github/workflows/fvt.yml
Labels: ignore-for-release
