Repository IBM/sarama, pull requests merged in 2024-08, with the labels that each got.

#2947 fix(consumer): maintain ordering of offset commit requests
  offset_manager.go
  offset_manager_test.go
Labels: fix

#2939 fix(producer): treat ErrKafkaStorageError as retriable
  async_producer.go
Labels: fix

#2933 feat: update go directive to 1.20
  examples/consumergroup/go.mod
  examples/consumergroup/go.sum
  examples/exactly_once/go.mod
  examples/exactly_once/go.sum
  examples/http_server/go.mod
  examples/http_server/go.sum
  examples/interceptors/go.mod
  examples/interceptors/go.sum
  examples/sasl_scram_client/go.mod
  examples/sasl_scram_client/go.sum
  examples/txn_producer/go.mod
  examples/txn_producer/go.sum
  go.mod
Labels: feat

#2969 chore: add newer kafka versions and bump Go in CI
  .github/workflows/apidiff.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/fuzz.yml
  .github/workflows/fvt-main.yml
  .github/workflows/fvt-pr.yml
  .github/workflows/fvt.yml
  .github/workflows/i386.yml
  .golangci.yml
  Dockerfile.kafka
  docker-compose.yml
  entrypoint.sh
  record_test.go
  utils.go
Labels: chore
