Repository IBM/sarama, pull requests merged in 2024-12, with the labels that each got.

#3026 feat: Prevent retry buffer in AsyncProducer to go OOM
  async_producer.go
  async_producer_test.go
  config.go
Labels: feat, needs-investigation

#3044 chore(deps): bump golang.org/x/net to v0.33.0
  examples/consumergroup/go.mod
  examples/consumergroup/go.sum
  examples/exactly_once/go.mod
  examples/exactly_once/go.sum
  examples/http_server/go.mod
  examples/http_server/go.sum
  examples/interceptors/go.mod
  examples/interceptors/go.sum
  examples/sasl_scram_client/go.mod
  examples/sasl_scram_client/go.sum
  examples/txn_producer/go.mod
  examples/txn_producer/go.sum
Labels: chore

#3043 chore(ci): bump actions versions to latest
  .github/workflows/apidiff.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/dependency-review.yml
  .github/workflows/fuzz.yml
  .github/workflows/fvt.yml
  .github/workflows/i386.yml
  .github/workflows/scorecard.yml
  .github/workflows/stale.yml
Labels: ignore-for-release

#3030 feat(admin): implement leader election api
  admin.go
  admin_test.go
  broker.go
  elect_leaders_request.go
  elect_leaders_request_test.go
  elect_leaders_response.go
  elect_leaders_response_test.go
  election_type.go
  mockresponses.go
  request.go
Labels: feat
