Repository IBM/sarama, pull requests merged in 2025-01, with the labels that each got.

#3048 chore: bump minimum go to 1.21
  .github/workflows/ci.yml
  go.mod
Labels: chore

#3045 chore(test): include kafka 4.0.0 in FV testing
  .github/workflows/fvt-main.yml
  .github/workflows/fvt-pr.yml
  Dockerfile.kafka
  create_topics_request.go
  delete_topics_request.go
  functional_consumer_test.go
  functional_producer_test.go
  functional_test.go
  server.properties
  utils.go
Labels: chore

#3055 fix(ci): restore the Kafka 4.0.0 FV
  .github/workflows/fvt.yml
  Dockerfile.kafka
  docker-compose.yml
  functional_test.go
Labels: ci

#3053 fix(admin): add retries for GroupCoordinator errors
  admin.go
  errors.go
  functional_admin_test.go
Labels: fix

#3066 chore(deps): update dependabot config
  .github/dependabot.yml
Labels: ignore-for-release

#3073 chore: add version constant for kafka 3.7.2
  utils.go
Labels: chore

#3074 chore(ci): bump 2.6.x FV to its last patch release
  .github/workflows/fvt-main.yml
  .github/workflows/fvt-pr.yml
Labels: ignore-for-release

#3079 chore(ci): fetch kafka 4.0 via tar.gz rather than git
  Dockerfile.kafka
Labels: chore

#3080 fix(ci): tighten up github workflows
  .github/workflows/fvt.yml
  .github/workflows/scorecard.yml
Labels: chore

#3076 fix(sasl): add nilguard around token to prevent panic
  broker.go
Labels: fix

#3081 fix(test): consumer group fetch request messages
  consumer_group_test.go
Labels: tests

#3088 feat(producer): add MaxBufferBytes to limit retry buffer size
  async_producer.go
  async_producer_test.go
  config.go
Labels: feat

#3085 chore(ci): analyse actions in codeql
  .github/workflows/codeql-analysis.yml
Labels: chore
