Repository IBM/sarama, pull requests merged in 2025-10, with the labels that each got.

#3320 feat: support DeleteGroups V2 protocol
  admin.go
  delete_groups_request.go
  delete_groups_request_test.go
  delete_groups_response.go
  delete_groups_response_test.go
  functional_admin_test.go
  request_test.go
Labels: feat

#3325 chore: add 3.9.1 and 4.1.0 version constants and FVT
  .github/workflows/fvt-main.yml
  .github/workflows/fvt-pr.yml
  .github/workflows/fvt.yml
  Dockerfile.kafka
  docker-compose.yml
  entrypoint.sh
  utils.go
Labels: chore

#3327 fix: decoder issues
  real_decoder.go
Labels: fix

#3326 refactor: get/put for KError
  acl_create_response.go
  acl_delete_response.go
  acl_describe_response.go
  add_offsets_to_txn_response.go
  add_partitions_to_txn_response.go
  alter_client_quotas_response.go
  alter_partition_reassignments_response.go
  alter_user_scram_credentials_response.go
  create_partitions_response.go
  create_topics_response.go
  delete_groups_response.go
  delete_offsets_response.go
  delete_records_response.go
  delete_topics_response.go
  describe_client_quotas_response.go
  describe_log_dirs_response.go
  describe_user_scram_credentials_response.go
  elect_leaders_response.go
  end_txn_response.go
  fetch_response.go
  find_coordinator_response.go
  heartbeat_response.go
  init_producer_id_response.go
  join_group_response.go
  leave_group_response.go
  list_groups_response.go
  list_partition_reassignments_response.go
  metadata_response.go
  offset_commit_response.go
  offset_fetch_response.go
  offset_response.go
  packet_decoder.go
  packet_encoder.go
  prep_encoder.go
  produce_response.go
  real_decoder.go
  real_encoder.go
  sasl_authenticate_response.go
  sasl_handshake_response.go
  sync_group_response.go
Labels: internal

#3333 fix: return correct error when encoding
  join_group_request.go
Labels: fix

#3337 fix: correct ApiVersionsResponse handling of ErrUnsupportedVersion
  api_versions_response.go
  api_versions_response_test.go
  encoder_decoder.go
Labels: fix
