Repository IBM/sarama, pull requests merged in 2025-09, with the labels that each got.

#3277 chore: refactor to use modern atomic types
  broker.go
  client.go
  consumer.go
  mocks/consumer.go
Labels: chore

#3279 feat: add SASLv1 support for Kerberos
  broker.go
  broker_test.go
  config.go
  gssapi_kerberos.go
  kerberos_client_test.go
Labels: feat

#3297 chore: apply modernize fixes from gopls
  admin.go
  balance_strategy.go
  balance_strategy_test.go
  broker.go
  broker_test.go
  client.go
  delete_records_request.go
  delete_records_response.go
  metrics_test.go
  mockbroker.go
  mocks/mocks.go
  tools/kafka-console-producer/kafka-console-producer.go
  zstd_test.go
Labels: chore

#3301 refactor: use struct rather than map with one entry
  admin.go
Labels: chore

#3305 fix: add V4 as valid CreateTopicsResponse
  create_topics_response.go
Labels: fix

#3307 fix: extend TestAllocateBodyProtocolVersions for more testing
  request_test.go
Labels: fix

#3311 chore(ci): adopt gotestsum and re-run flakes
  .github/workflows/ci.yml
  .github/workflows/fvt.yml
  Makefile
Labels: ci
